create table if not exists departments (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default now()
);

create table if not exists designations (
  id bigint generated by default as identity primary key,
  name text not null,
  grade text,
  created_at timestamp with time zone default now()
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null,
  pf_number text unique,
  mobile_number text,
  dob date,
  nid text,
  gender text,
  employee_status text,
  about text,
  blood_group text,
  home_district text,
  present_address text,
  permanent_address text,
  bank_name text,
  ac_no text,
  joining_date date,
  prl_date date,
  email text unique,
  dept_id bigint references departments (id) on delete set null,
  desig_id bigint references designations (id) on delete set null,
  basic_salary numeric(12, 2) default 0,
  created_at timestamp with time zone default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint references employees (id) on delete cascade,
  date date not null,
  status text check (status in ('Present', 'Absent')),
  created_at timestamp with time zone default now(),
  unique (employee_id, date)
);

create table if not exists leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint references employees (id) on delete cascade,
  leave_type text,
  start_date date not null,
  end_date date not null,
  status text default 'Pending',
  reason text,
  created_at timestamp with time zone default now()
);

create table if not exists holidays (
  id bigint generated by default as identity primary key,
  date date not null,
  title text not null,
  created_at timestamp with time zone default now(),
  unique (date, title)
);

create table if not exists payroll_runs (
  id bigint generated by default as identity primary key,
  month text not null,
  total_amount numeric(12, 2) default 0,
  status text default 'Draft',
  processed_at timestamp with time zone
);
